### ISSUE TITLE
Feature request: option to export additional columns in omefile_2_analysisfolder

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/imctools#107]
* imctools version: 2.1.0
* Python version: NA
* Operating System: NA

### Description

When exporting a csv that contains the order of the metal tags using the `omefile_2_analysisfolder` function, what is the reasoning behind selecting only the `metalcolumn`? I'd propose to add a parameter `export_all_meta = False` that when set to `True` either exports all columns from the panel or other metadata from the .ome.tiff. This would make it easier to link metal tags to the target names for e.g. ilastik training or when opening the files in ImageJ. I'm happy to discuss this.

**Comment by votti** [comment]
Hi,
The reason was to limit data/information duplication to a minimum:
Keeping metadata in a file like the `panel.csv` as compared to copy this information around makes it clearer that this is the single source of truth for channel metadata and makes it way easier eg to rename channel names (which is extremely common as there is no single standard how to annotate antibody channel names).

Also I do not see how this makes it technically would make It significantly easier to link target names to images for ilastik training or ImageJ, but maybe I am missing something,

Anyways, if you are convinced this is a good idea, feel free to add it.

**Comment by nilseling** [comment]
Hey, agreed on data duplication. Especially since these files are generated for each exported `.tiff` (you could think about exporting them per .mcd since you want to enforce a consistent naming scheme anyway). I just find it a bit inconvenient to lookup the target name in the panel based on the metal order in the exported `.csv` since the entries are not ordered the same way unless you manually reorder the panel by metal tag.  But yes, if it annoys me in the future, I'll add it ;)

**Comment by jwindhager** [comment]
Still an open issue?

**Comment by jwindhager** [comment]
Well, closing for now
