### ISSUE TITLE
Cellprofiler 3

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/imctools#38]
Hi is imctools compatible with CP3?  Not sure if i missed an update.

Also is there a module that performs a median filter in a 3x3 area?

Thank you again
AC

**Comment by votti** [comment]
`imctools` itself is fairly independent on the CellProfiler version used as it only does the conversion of files into a CP compatible format. However, the `ImcPluginsCP` have indeed been updated for CP3 compatiblity (https://github.com/BodenmillerGroup/ImcPluginsCP/releases) and the example usage segmentation pipeline has been adapted to be fully CP3 compatible, with an example preprocessing script, detailed instructions and example CP3 pipelines (https://github.com/BodenmillerGroup/ImcSegmentationPipeline, still a bit work in progress as I am trying to streamline things, but otherwise fully functional).

What I now do recommend particularly for CP3 is setting in `ometiff_2_analysis` the  `pixeltype='uint16'`, as this should speed up the processing and is more CP3 compatible.

As for the median filtering: use the `SmoothMultichannel` module (https://github.com/BodenmillerGroup/ImcPluginsCP/blob/master/plugins/smoothmultichannel.py), where `Median` filter is an option. Set `Artefact Diameter` to 3 for a 3x3 filter.

Cheers, Vito

**Comment by arcolombo** [comment]
thank you
