### ISSUE TITLE
Warning Message when Converting ome.tiffs to a HistoCAT compatible format

### ISSUE THREAD

**Issue by aagamboa** [BodenmillerGroup/imctools#88]
I got the following warning message for the chunk of code "Convert ome.tiffs to a HistoCAT compatible format" 

C:\Users\GamboaA1\.conda\envs\imctools\lib\site-packages\imctools\io\__init__.py:41: UserWarning: Data max trunkated as outside dtype range
  warnings.warn(CHANGE_DTYPE_UB_WARNING)

 Have you come across this warning message before? All of the ome.tiffs were still generated, so I'm not sure if I should be concerned about it. 

Thank you!
Alicia

**Comment by votti** [comment]
Hi Alicia,

This means some channels have pixels with more than 65535 counts per pixel, which is REALLY high in IMC and usually corresponds to outlier pixels and is most likely outside the dynamic range of the instrument.

The technical reason behind this warning is:
We save the image values in `.ome.tiff` as floating point images, that corresponds to the original raw data format and can be any value. HistoCAT is requiring 16 bit images (= images with values between 0 and 2^16-1=65535).
The behaviour of imctools is to `truncate` values outside this range, e.g. values larger than 65535 are set to 65535, to generate HistoCAT compatible images.

As said values that high are usually not reliable and should be really rare, thus I would not be concerned.

If you actually have a lot of channels where the values routinely go that high (eg whole regions of the image have > 65535 counts) I would be concerned - both as the analysis would be likely rather unreliable as you are outside the linear range of the machine and as the machine detector likely could take damage due to an exceedingly high metal ion number. In such a case I would recommend to decrease the antibody concentration.

Cheers, Vito

**Comment by aagamboa** [comment]
Thank you so much! I appreciate your quick and descriptive response, it was very helpful.
